### PR TITLE
Image embeds

### LINKED ISSUE #1: Email Server Should Download and Re-Upload Inline Images
Email messages sent from Gmail (like Matt's blog posts) are embedding images and hosting them on Google servers instead of adding them as attachments. Later, when these are posted on the blog, they sometimes don't display, and who knows how long they will stay hosted at the same URL. The desired behavior is probably for the email server to download all inline images and re-upload them to the Team 254 server, replacing the embed URLs along the way.

See below images not rendering:
https://www.team254.com/frc-day-4-build-blog/
image

### PR DESCRIPTION
**Pull request by SumiGovindaraju**
Adds all non `media.team254.com/attachments` img srcs to the attachments library, and then replaces these srcs with the correct URL. Closes #1.

### CODE REVIEW

**Comment by SumiGovindaraju** [comment]
[Fix Cheesy Mail to automatically upload images](https://trello.com/c/szQJIlVx/2-fix-cheesy-mail-to-automatically-upload-images)

**Comment by patfair** [comment]
@SumiGovindaraju I'm not sure that it's working. I deployed the change and sent an email with an external image in it (putting DEBUG in the subject so that it only goes to me) and I don't think anything happened.

**Comment by SumiGovindaraju** [comment]
@patfair: I checked `cheesy-mail.log` and there were no errors thrown. I will explore this issue more.

**Comment by patfair** [comment]
Sorry, I meant to say that I did get the email as expected, but the image URL was the same one as in the original message.

**Comment by SumiGovindaraju** [comment]
@patfair: Try the debug email now. I already deployed.

**Comment by patfair** [comment]
Nope, still not rewriting the URL.

**Comment by SumiGovindaraju** [comment]
RIP. Ok, I'll work on it. I just send debug emails by adding DEBUG to the subject line, right?

**Comment by patfair** [comment]
Right.

**Comment by SumiGovindaraju** [comment]
@patfair: Fixed in d12e689102cddeff66b7ad5f25d517f276eb5f45. The code was not executing because of an if statement.

**Pull request merged**
